---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: talos-node-gpu-1
  namespace: openebs-system
spec:
  node: talos-node-gpu-1
  disks: ["/dev/sda"]

---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: talos-node-large-1
  namespace: openebs-system
spec:
  node: talos-node-large-1
  disks: ["/dev/sda"]

---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: talos-node-large-2
  namespace: openebs-system
spec:
  node: talos-node-large-2
  disks: ["/dev/sda"]

---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: talos-node-large-3
  namespace: openebs-system
spec:
  node: talos-node-large-3
  disks: ["/dev/sda"]

