---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ${SECRET_DOMAIN/./-}-staging-tls
  labels:
    controller.cert-manager.io/fao: "true"
  annotations:
    cert-manager.io/alt-names: '*.${SECRET_DOMAIN},${SECRET_DOMAIN}'
    cert-manager.io/certificate-name: "${SECRET_DOMAIN/./-}-staging"
    cert-manager.io/common-name: ${SECRET_DOMAIN}
    cert-manager.io/ip-sans: ""
    cert-manager.io/issuer-group: ""
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-staging
    cert-manager.io/uri-sans: ""
    secrets.infisical.com/auto-reload: "true"
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 1
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infiscal-auth-secret
        secretNamespace: external-secrets
      secretsScope:
        projectSlug: homelab-p-iqd # <-- project slug
        envSlug: staging # "dev", "staging", "prod", etc..
        secretsPath: "/Certificates/${SECRET_DOMAIN/./-}"
  managedKubeSecretReferences:
    - secretName: ${SECRET_DOMAIN/./-}-staging-tls
      secretNamespace: cert-manager
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true

---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ${SECRET_DOMAIN_MEDIA/./-}-staging-tls
  labels:
    controller.cert-manager.io/fao: "true"
  annotations:
    cert-manager.io/alt-names: '*.${SECRET_DOMAIN_MEDIA},${SECRET_DOMAIN_MEDIA}'
    cert-manager.io/certificate-name: "${SECRET_DOMAIN_MEDIA/./-}-staging"
    cert-manager.io/common-name: ${SECRET_DOMAIN_MEDIA}
    cert-manager.io/ip-sans: ""
    cert-manager.io/issuer-group: ""
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-staging
    cert-manager.io/uri-sans: ""
    secrets.infisical.com/auto-reload: "true"
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 1
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infiscal-auth-secret
        secretNamespace: external-secrets
      secretsScope:
        projectSlug: homelab-p-iqd # <-- project slug
        envSlug: staging # "dev", "staging", "prod", etc..
        secretsPath: "/Certificates/${SECRET_DOMAIN_MEDIA/./-}"
  managedKubeSecretReferences:
    - secretName: ${SECRET_DOMAIN_MEDIA/./-}-staging-tls
      secretNamespace: cert-manager
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true

---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ${SECRET_DOMAIN_PERSONAl/./-}-staging-tls
  labels:
    controller.cert-manager.io/fao: "true"
  annotations:
    cert-manager.io/alt-names: '*.${SECRET_DOMAIN_PERSONAL},${SECRET_DOMAIN_PERSONAL}'
    cert-manager.io/certificate-name: "${SECRET_DOMAIN_PERSONAL/./-}-staging"
    cert-manager.io/common-name: ${SECRET_DOMAIN_PERSONAL}
    cert-manager.io/ip-sans: ""
    cert-manager.io/issuer-group: ""
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-staging
    cert-manager.io/uri-sans: ""
    secrets.infisical.com/auto-reload: "true"
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 1
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infiscal-auth-secret
        secretNamespace: external-secrets
      secretsScope:
        projectSlug: homelab-p-iqd # <-- project slug
        envSlug: staging # "dev", "staging", "prod", etc..
        secretsPath: "/Certificates/${SECRET_DOMAIN_PERSONAL/./-}"
  managedKubeSecretReferences:
    - secretName: ${SECRET_DOMAIN_PERSONAL/./-}-staging-tls
      secretNamespace: cert-manager
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true