---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../flux/components/common
resources:
  #- ./autobrr/ks.yaml
  - ./bazarr/ks.yaml
  - ./tautulli/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./sonarr-uhd/ks.yaml
  - ./radarr/ks.yaml
  - ./radarr-uhd/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./overseerr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./plex/ks.yaml
  - ./wizarr/ks.yaml
