---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: emqx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: emqx-secret
    template:
      engineVersion: v2
      data:
        EMQX_DASHBOARD__DEFAULT_USERNAME: "{{ .EMQX_DASHBOARD_DEFAULT_USERNAME }}"
        EMQX_DASHBOARD__DEFAULT_PASSWORD: "{{ .EMQX_DASHBOARD_DEFAULT_PASSWORD }}"
  dataFrom:
    - find:
        path: EMQX_DASHBOARD_DEFAULT_USERNAME
    - find:
        path: EMQX_DASHBOARD_DEFAULT_PASSWORD
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: emqx-init-user
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: emqx-init-user-secret
    template:
      engineVersion: v2
      data:
        init-user.json: |
          [{"user_id": "{{ .EMQX_MQTT_USERNAME }}", "password": "{{ .EMQX_MQTT_PASSWORD }}", "is_superuser": true},{{"user_id": "{{ .EMQX_MQTT_HOME_USERNAME }}", "password": "{{ .EMQX_MQTT_HOME_PASSWORD }}", "is_super_user":false}]

  dataFrom:
    - find:
        path: EMQX_MQTT_USERNAME
    - find:
        path: EMQX_MQTT_PASSWORD
    - find:
        path: EMQX_MQTT_HOME_USERNAME
    - find:
        path: EMQX_MQTT_HOME_PASSWORD
