---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt-garage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: zigbee2mqtt-garage-secret
    template:
      engineVersion: v2
      data:
        ZIGBEE2MQTT_CONFIG_MQTT_USER: "{{ .EMQX_MQTT_HOME_USERNAME }}"
        ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: "{{ .EMQX_MQTT_HOME_PASSWORD }}"
        ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: "{{ .ZIGBEE_PAN_ID }} "
        ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: "{{ .ZIGBEE_EXT_PAN_ID }}"
        ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: "{{ .ZIGBEE_NETWORK_KEY }}"
  dataFrom:
    - find:
        path: EMQX_MQTT_HOME_USERNAME
    - find:
        path: EMQX_MQTT_HOME_PASSWORD
    - find:
       path: ZIGBEE_PAN_ID
    - find:
        path: ZIGBEE_EXT_PAN_ID
    - find:
        path: ZIGBEE_NETWORK_KEY
