---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-uhd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: sonarr-uhd-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        SONARR__AUTH__APIKEY: "{{ .SONARR_UHD_API_KEY }}"
        PUSHOVER_API_TOKEN: "{{ .PUSHOVER_API_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"

  dataFrom:
    - find:
        path: SONARR_UHD_API_KEY
    - find:
        path : PUSHOVER_API_TOKEN
    - find:
        path: PUSHOVER_USER_KEY
