---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: vaultwarden-secret
    template:
      engineVersion: v2
      data:
        # App
        ADMIN_TOKEN: "{{ .VAULTWARDEN_ARGON2_TOKEN }}"
  dataFrom:
    - find:
        path: VAULTWARDEN_ARGON2_TOKEN

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-postgres
  target:
    name: vaultwarden-postgres-secret
    template:
      engineVersion: v2
      data:
        # App
        DATABASE_URL: postgresql://{{ .VAULTWARDEN_POSTGRES_USER }}:{{ .VAULTWARDEN_POSTGRES_PASS }}@{{ .POSTGRES_SUPER_HOST_RW }}.database.svc.cluster.local/vaultwarden

        # Postgres Init
        INIT_POSTGRES_DBNAME: &dbName vaultwarden
        INIT_POSTGRES_HOST: &dbHost "{{ .POSTGRES_SUPER_HOST_RW }}.database.svc.cluster.local"
        INIT_POSTGRES_USER: &dbUser "{{ .VAULTWARDEN_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .VAULTWARDEN_POSTGRES_PASS }}"
        # TODO: check on this one
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - find:
        name:
          regexp: ^VAULTWARDEN.*
    - find:
        path: POSTGRES_SUPER_PASS
    - find:
        path: POSTGRES_SUPER_HOST_RW


