---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name authentik
spec:
  secretStoreRef:
    name: infisical-authentik
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: authentik-secret
    template:
      engineVersion: v2
      data:
        # Authentik
        AUTHENTIK_BOOTSTRAP_EMAIL: '{{ .AUTHENTIK_EMAIL }}'
        AUTHENTIK_BOOTSTRAP_PASSWORD: '{{ .AUTHENTIK_PASSWORD }}'
        AUTHENTIK_BOOTSTRAP_TOKEN: '{{ .AUTHENTIK_TOKEN }}'
        AUTHENTIK_SECRET_KEY: '{{ .AUTHENTIK_SECRET_KEY }}'
  dataFrom:
    - find:
        name:
          regexp: ^AUTHENTIK.*
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-postgres
  target:
    name: authentik-postgres-secret
    template:
      engineVersion: v2
      data:
        # App
        DATABASE_URL: postgresql://{{ .AUTHENTIK_POSTGRES_USER }}:{{ .AUTHENTIK_POSTGRES_PASS }}@{{ .POSTGRES_SUPER_HOST_RW }}.database.svc.cluster.local/authentik

        # Postgres Init
        INIT_POSTGRES_DBNAME: &dbName authentik
        INIT_POSTGRES_HOST: &dbHost "{{ .POSTGRES_SUPER_HOST_RW }}.database.svc.cluster.local"
        INIT_POSTGRES_USER: &dbUser "{{ .AUTHENTIK_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .AUTHENTIK_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"

        AUTHENTIK_POSTGRESQL__NAME: *dbName
        AUTHENTIK_POSTGRESQL__HOST: *dbHost
        AUTHENTIK_POSTGRESQL__USER: *dbUser
        AUTHENTIK_POSTGRESQL__PASSWORD: *dbPass

  dataFrom:
    - find:
        name:
          regexp: ^AUTHENTIK.*
    - find:
        path: POSTGRES_SUPER_USER
    - find:
        path: POSTGRES_SUPER_PASS
    - find:
        path: POSTGRES_SUPER_HOST_RW
