---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nut-upsd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: nut-upsd-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        API_PASSWORD: "{{ .NUT_API_PASSWORD }}"

  dataFrom:
    - find:
        path: NUT_API_PASSWORD

