---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: actions-runner-controller-secret
    template:
      engineVersion: v2
      data:
        ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID: |-
          {{ .ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID }}
        ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID: |-
          {{ .ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID }}
        ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY: |-
          {{ .ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY }}
        ACTION_RUNNER_CONTROLLER_GITHUB_WEBHOOK_SECRET_TOKEN: |-
          {{ .ACTION_RUNNER_CONTROLLER_GITHUB_WEBHOOK_SECRET_TOKEN }}
  dataFrom:
    - find:
        path: ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID
    - find:
        path: ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID
    - find:
       path: ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY
    - find:
        path: ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY
