---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
components:
  - ../../flux/components/common
resources:
  - ./actual/ks.yaml
  - ./atuin/ks.yaml
  - ./unifi/ks.yaml
  - ./paperless-ngx/ks.yaml
  - ./searxng/ks.yaml
  - ./obsidian-couchdb/ks.yaml
  - ./resume/ks.yaml


