---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-ngx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: paperless-ngx-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        PAPERLESS_DBHOST: "{{ .POSTGRES_SUPER_HOST_RW }}.database.svc.cluster.local"
        PAPERLESS_DBNAME: "paperless"
        PAPERLESS_DBUSER: "{{ .PAPERLESS_POSTGRES_USER }}"
        PAPERLESS_DBPASS: "{{ .PAPERLESS_POSTGRES_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_REDIS: "redis://dragonfly.database.svc.cluster.local"
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"

  dataFrom:
    - find:
        name:
          regexp: ^PAPERLESS.*
    - find:
        path: POSTGRES_SUPER_HOST_RW

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-ngx-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: paperless-ngx-postgres-secret
    template:
      engineVersion: v2
      data:
        # Postgres Init
        INIT_POSTGRES_DBNAME: paperless
        INIT_POSTGRES_HOST: "{{ .POSTGRES_SUPER_HOST_RW }}.database.svc.cluster.local"
        INIT_POSTGRES_USER: "{{ .PAPERLESS_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .PAPERLESS_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"

  dataFrom:
    - find:
        name:
          regexp: ^PAPERLESS.*
    - find:
        path: POSTGRES_SUPER_USER
    - find:
        path: POSTGRES_SUPER_PASS
    - find:
        path: POSTGRES_SUPER_HOST_RW
