---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets
            name: infiscal-auth-secret
          clientSecret:
            key: clientSecret
            namespace: external-secrets
            name: infiscal-auth-secret
      # Details to pull secrets from
      secretsScope:
        projectSlug: homelab-p-iqd
        environmentSlug: prod # "dev", "staging", "prod", etc..
        secretsPath: /
        recursive: true
      # optional
      hostAPI: https://app.infisical.com
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical-postgres
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets
            name: infiscal-auth-secret
          clientSecret:
            key: clientSecret
            namespace: external-secrets
            name: infiscal-auth-secret
      # Details to pull secrets from
      secretsScope:
        projectSlug: homelab-p-iqd
        environmentSlug: prod # "dev", "staging", "prod", etc..
        secretsPath: /Infrastructure/Postgres
        recursive: true
      # optional
      hostAPI: https://app.infisical.com
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical-hass
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets
            name: infiscal-auth-secret
          clientSecret:
            key: clientSecret
            namespace: external-secrets
            name: infiscal-auth-secret
      # Details to pull secrets from
      secretsScope:
        projectSlug: homelab-p-iqd
        environmentSlug: prod # "dev", "staging", "prod", etc..
        secretsPath: /Infrastructure/HomeAssistant
        recursive: true
      # optional
      hostAPI: https://app.infisical.com

