---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: github-token-secret
    template:
      engineVersion: v2
      data:
        github-token-secret: "{{ .FLUX_GITHUB_TOKEN }}"

  dataFrom:
    - find:
        path: FLUX_GITHUB_TOKEN
