---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-postgres
  target:
    name: cloudnative-pg-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - find:
        path: POSTGRES_SUPER_USER
    - find:
        path: POSTGRES_SUPER_PASS

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: cloudnative-pg-minio-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        accessKeyId: "{{ .POSTGRES_MINIO_ACCESS_KEY }}"
        secretAccessKey: "{{ .POSTGRES_MINIO_SECRET_KEY }}"

  dataFrom:
    - find:
        path: POSTGRES_MINIO_ACCESS_KEY
    - find:
        path: POSTGRES_MINIO_SECRET_KEY

