---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync-r2"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: "${APP}-volsync-r2-secret"
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .CLOUDFLARE_S2_URL }}/${APP}"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .CLOUDFLARE_OBJECT_STORAGE_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .CLOUDFLARE_OBJECT_STORAGE_SECRET_ACCESS_KEY }}"
  dataFrom:
    - find:
        path: RESTIC_PASSWORD
    - find:
        path: CLOUDFLARE_S2_URL
    - find:
        path: CLOUDFLARE_OBJECT_STORAGE_SECRET_ACCESS_KEY
    - find:
        path: CLOUDFLARE_OBJECT_STORAGE_KEY_ID
