---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}-r2"
spec:
  sourcePVC: "${APP}"
  trigger:
    schedule: "30 0 * * *"
  restic:
    copyMethod: "${VOLSYNC_COPYMETHOD:-Snapshot}"
    pruneIntervalDays: 14
    repository: "${APP}-volsync-r2-secret"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-csi-mayastor-snapclass}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-10Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-mayastor-single-replica}"
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
    storageClassName: "${VOLSYNC_STORAGECLASS:-mayastor-single-replica}"
    accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:-1000}
      runAsGroup: ${VOLSYNC_PGID:-150}
      fsGroup: ${VOLSYNC_PGID:-140}
    retain:
      daily: 7
