---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}"
spec:
  secretName: "${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "media,database,home-automation,security,default,storage,flux-system,kube-system,network,observability,selfhosted"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "media,home-automation,database,default,security,storage,flux-system,kube-system,network,observability,selfhosted" # Control auto-reflection namespaces

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_MEDIA/./-}"
spec:
  secretName: "${SECRET_DOMAIN_MEDIA/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN_MEDIA}"
  dnsNames:
    - "${SECRET_DOMAIN_MEDIA}"
    - "*.${SECRET_DOMAIN_MEDIA}"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "media,default,flux-system,kube-system,network,observability,selfhosted"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "media,default,flux-system,kube-system,network,observability,selfhosted" # Control auto-reflection namespaces

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_PERSONAL/./-}"
spec:
  secretName: "${SECRET_DOMAIN_PERSONAL/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN_PERSONAL}"
  dnsNames:
    - "${SECRET_DOMAIN_PERSONAL}"
    - "*.${SECRET_DOMAIN_PERSONAL}"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "media,default,flux-system,kube-system,network,observability,selfhosted"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "media,default,flux-system,kube-system,network,observability,selfhosted" # Control auto-reflection namespaces



---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_DIVING/./-}"
spec:
  secretName: "${SECRET_DOMAIN_DIVING/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN_DIVING}"
  dnsNames:
    - "${SECRET_DOMAIN_DIVING}"
    - "*.${SECRET_DOMAIN_DIVING}"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "media,default,flux-system,kube-system,network,observability,selfhosted"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "media,default,flux-system,kube-system,network,observability,selfhosted" # Control auto-reflection namespaces

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_WIFE/./-}"
spec:
  secretName: "${SECRET_DOMAIN_WIFE/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN_WIFE}"
  dnsNames:
    - "${SECRET_DOMAIN_WIFE}"
    - "*.${SECRET_DOMAIN_WIFE}"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "media,default,flux-system,kube-system,network,observability,selfhosted"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "media,default,flux-system,kube-system,network,observability,selfhosted" # Control auto-reflection namespaces




