---
  apiVersion: secrets.infisical.com/v1alpha1
  kind: InfisicalPushSecret
  metadata:
    name: "${SECRET_DOMAIN/./-}-staging-tls"
  spec:
    resyncInterval: 1m
    hostAPI: https://app.infisical.com/api

    # Optional, defaults to no replacement.
    updatePolicy: Replace # If set to replace, existing secrets inside Infisical will be replaced by the value of the PushSecret on sync.

    # Optional, defaults to no deletion.
    deletionPolicy: None # If set to delete, the secret(s) inside Infisical managed by the operator, will be deleted if the InfisicalPushSecret CRD is deleted.

    destination:
      projectId: 19edb415-e2e8-4dac-8583-5c470e66d0d1
      environmentSlug: prod
      secretsPath: /Certificates
    push:
      secret:
        secretName: "${SECRET_DOMAIN/./-}-staging-tls"
        secretNamespace: cert-manager

    authentication:
      universalAuth:
        credentialsRef:
          secretName: infiscal-auth-secret
          secretNamespace: external-secrets
---
  apiVersion: secrets.infisical.com/v1alpha1
  kind: InfisicalPushSecret
  metadata:
    name: "${SECRET_DOMAIN_MEDIA/./-}-staging-tls"
  spec:
    resyncInterval: 1m
    hostAPI: https://app.infisical.com/api

    # Optional, defaults to no replacement.
    updatePolicy: Replace # If set to replace, existing secrets inside Infisical will be replaced by the value of the PushSecret on sync.

    # Optional, defaults to no deletion.
    deletionPolicy: None # If set to delete, the secret(s) inside Infisical managed by the operator, will be deleted if the InfisicalPushSecret CRD is deleted.

    destination:
      projectId: 19edb415-e2e8-4dac-8583-5c470e66d0d1
      environmentSlug: prod
      secretsPath: /Certificates
    push:
      secret:
        secretName: "${SECRET_DOMAIN_MEDIA/./-}-staging-tls"
        secretNamespace: cert-manager

    authentication:
      universalAuth:
        credentialsRef:
          secretName: infiscal-auth-secret
          secretNamespace: external-secrets
---
  apiVersion: secrets.infisical.com/v1alpha1
  kind: InfisicalPushSecret
  metadata:
    name: "${SECRET_DOMAIN_PERSONAL/./-}-staging-tls"
  spec:
    resyncInterval: 1m
    hostAPI: https://app.infisical.com/api

    # Optional, defaults to no replacement.
    updatePolicy: Replace # If set to replace, existing secrets inside Infisical will be replaced by the value of the PushSecret on sync.

    # Optional, defaults to no deletion.
    deletionPolicy: None # If set to delete, the secret(s) inside Infisical managed by the operator, will be deleted if the InfisicalPushSecret CRD is deleted.

    destination:
      projectId: 19edb415-e2e8-4dac-8583-5c470e66d0d1
      environmentSlug: prod
      secretsPath: /Certificates
    push:
      secret:
        secretName: "${SECRET_DOMAIN_PERSONAL/./-}-staging-tls"
        secretNamespace: cert-manager

    authentication:
      universalAuth:
        credentialsRef:
          secretName: infiscal-auth-secret
          secretNamespace: external-secrets
---
  apiVersion: secrets.infisical.com/v1alpha1
  kind: InfisicalPushSecret
  metadata:
    name: "${SECRET_DOMAIN_DIVING/./-}-staging-tls"
  spec:
    resyncInterval: 1m
    hostAPI: https://app.infisical.com/api

    # Optional, defaults to no replacement.
    updatePolicy: Replace # If set to replace, existing secrets inside Infisical will be replaced by the value of the PushSecret on sync.

    # Optional, defaults to no deletion.
    deletionPolicy: None # If set to delete, the secret(s) inside Infisical managed by the operator, will be deleted if the InfisicalPushSecret CRD is deleted.

    destination:
      projectId: 19edb415-e2e8-4dac-8583-5c470e66d0d1
      environmentSlug: prod
      secretsPath: /Certificates
    push:
      secret:
        secretName: "${SECRET_DOMAIN_DIVING/./-}-staging-tls"
        secretNamespace: cert-manager

    authentication:
      universalAuth:
        credentialsRef:
          secretName: infiscal-auth-secret
          secretNamespace: external-secrets
---
  apiVersion: secrets.infisical.com/v1alpha1
  kind: InfisicalPushSecret
  metadata:
    name: "${SECRET_DOMAIN_WIFE/./-}-staging-tls"
  spec:
    resyncInterval: 1m
    hostAPI: https://app.infisical.com/api

    # Optional, defaults to no replacement.
    updatePolicy: Replace # If set to replace, existing secrets inside Infisical will be replaced by the value of the PushSecret on sync.

    # Optional, defaults to no deletion.
    deletionPolicy: None # If set to delete, the secret(s) inside Infisical managed by the operator, will be deleted if the InfisicalPushSecret CRD is deleted.

    destination:
      projectId: 19edb415-e2e8-4dac-8583-5c470e66d0d1
      environmentSlug: prod
      secretsPath: /Certificates
    push:
      secret:
        secretName: "${SECRET_DOMAIN_WIFE/./-}-staging-tls"
        secretNamespace: cert-manager

    authentication:
      universalAuth:
        credentialsRef:
          secretName: infiscal-auth-secret
          secretNamespace: external-secrets
