---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./csi-driver-nfs/ks.yaml
  - ./minio/ks.yaml
  - ./snapshot-controller/ks.yaml
components:
  - ../../flux/components/namespace
patches:
  - # Add the name to the namespace
    patch: |
      - op: add
        path: /metadata/name
        value: storage
    target:
      kind: Namespace
